name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #downloading code to the runners server
      - name: Get code
      #this keyword is used to define an action and not a shell script
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        #this keyword is used to configure the action
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test 
            
        